### PR TITLE
adds asynchronous loading + the ability to cancel processing + UI for monitoring model status

### PR DESCRIPTION
**Pull request by hugofloresgarcia**
fixes for #47 #70 #71  #45 #46 #76

### CODE REVIEW

**Comment by hugofloresgarcia** [comment]
fixes #47

**Comment by hugofloresgarcia** [comment]
fixes #70

**Comment by hugofloresgarcia** [comment]
fixes #71

**Comment by hugofloresgarcia** [comment]
fixes #46

**Comment by hugofloresgarcia** [comment]
#76

**Review by xribene — APPROVED** [review]
J'approuve

**Comment by hugofloresgarcia** [comment]
also fixes #73

**Pull request merged**
